apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webhook-deployment
  namespace: kube-system
  labels:
    app: flavor-validate
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: flavor-validate
    spec:
      serviceAccountName: namespace-controller
      containers:
        - name: flavor-validate
          image: webhook:v1
          imagePullPolicy: IfNotPresent
          args:
            - -gpu-alias=nvidia.com/gpu
            - -alsologtostderr
            - -v=4
            - 2>&1
          ports:
          - containerPort: 443
          volumeMounts:
          - name: webhook-certs
            mountPath: /etc/webhook/certs
            readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
